-- Migration 005: upstream production DB tables (A 库备份)
-- Maps to source_records/节目数据.csv and source_records/子节目数据.csv

create table if not exists upstream_programs (
    id integer primary key,
    country_count text,
    country_codes text,
    country_code_property_types text,
    multi_language_count text,
    multi_language_ids text,
    language_ids text,
    multi_language_names text,
    multi_language_summaries text,
    multi_language_bright_spots text,
    multi_language_update_infos text,
    multi_language_json text,
    imdb_id text,
    code text,
    program_status text,
    make_by_star text,
    name text not null,
    make_year text,
    program_number text,
    episodes text,
    poster_type text,
    delete_flag text,
    metadata_modify_flag text,
    online_flag text,
    encryption_type text,
    tenant_id text,
    update_status text,
    first_publish_time text,
    fk_publisher_id text,
    download_right text,
    download_right_info text,
    status_explanation text,
    turn_on_watermark text,
    watermark_location text,
    create_id text,
    create_instant text,
    modify_id text,
    modify_instant text
);

create table if not exists upstream_episodes (
    id integer primary key,
    country_count text,
    country_codes text,
    country_code_available text,
    multi_language_count text,
    multi_language_ids text,
    language_ids text,
    multi_language_names text,
    multi_language_summaries text,
    multi_language_bright_spots text,
    multi_language_update_infos text,
    multi_language_json text,
    code text,
    name text not null,
    episode text,
    paragraph text,
    duration_hour text,
    duration_minute text,
    duration_second text,
    fk_program_content_id integer,
    fk_video_ondemand_id text,
    video_status text,
    effective_time text,
    source_type text,
    delete_flag text,
    metadata_modify_flag text,
    online_flag text,
    direct_weight text,
    tenant_id text,
    first_publish_time text,
    dot_status text,
    prologue_time text,
    epilogue_time text,
    support_download text,
    support_download_remarks text,
    original_publisher text,
    original_source text,
    import_video_name text,
    create_id text,
    create_instant text,
    modify_id text,
    modify_instant text,
    pc_id text,
    pc_imdb_id text,
    pc_code text,
    pc_name text,
    pc_type text,
    pc_program_status text
);

create index if not exists idx_upstream_episodes_fk
on upstream_episodes(fk_program_content_id);
